tags:
  load_all: true
  exclude: [created_by, source]

generalized_tables:
  landusages_gen38:
    source: landusages
    sql_filter: ST_Area(geometry) > 361
    tolerance: 38
  roads_gen1200:
    source: roads_gen300
    sql_filter: type IN ('motorway', 'trunk')  OR (type = 'construction' AND construction IN ('motorway', 'trunk'))
    tolerance: 1200
  roads_gen300:
    source: roads_gen75
    sql_filter: type IN ('motorway', 'trunk', 'primary') OR (type = 'construction' AND construction IN ('motorway', 'trunk', 'primary'))
    tolerance: 300
  roads_gen75:
    source: roads_gen9
    sql_filter: type IN ('motorway', 'trunk', 'primary', 'motorway_link', 'trunk_link',
      'secondary', 'primary_link', 'secondary_link', 'tertiary', 'tertiary_link',
      'runway', 'construction') OR (type IN ('rail', 'subway') AND NOT service IN('yard', 'siding',
      'spur'))
    tolerance: 75
  roads_gen9:
    source: roads
    sql_filter: type IN ('motorway', 'trunk', 'primary', 'motorway_link', 'trunk_link',
      'secondary', 'primary_link', 'secondary_link', 'tertiary', 'tertiary_link',
      'runway', 'taxiway', 'residential', 'unclassified', 'road', 'living_street',
      'track', 'service', 'pedestrian', 'construction') OR (type IN ('rail', 'subway') AND NOT service
      IN('yard', 'siding', 'spur'))
    tolerance: 9
  waterways_gen150:
    source: waterways_gen38
    sql_filter: type = 'river'
    tolerance: 150
  waterways_gen38:
    source: waterways_gen9
    sql_filter: type IN ('river', 'stream', 'canal')
    tolerance: 38
  waterways_gen9:
    source: waterways
    sql_filter: type IN ('river', 'stream', 'canal')
    tolerance: 9
tables:
  admin:
    type: polygon
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - key: left:country
      name: left
      type: string
    - key: right:country
      name: right
      type: string
    - key: admin_level
      name: admin_level
      type: integer
    - key: name
      name: name
      type: string
    filters:
      exclude_tags:
      - [maritime, 'yes']
    mapping:
      boundary:
      - administrative
  amenity_areas:
    # werden auch fuer buildings cadastre=no verwendet
    type: polygon
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: validated_geometry
    - key: name
      name: name
      type: string
    - name: type
      type: mapping_value
    - name: tags
      type: hstore_tags
    mapping:
      amenity:
      - __any__
      leisure:
      - __any__
      shop:
      - __any__
      tourism:
      - __any__
      building:
      - __any__
      natural:
      - __any__
      historic:
      - __any__
      information:
      - __any__
      government:
      - __any__
  amenity_points:
    type: point
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - key: name
      name: name
      type: string
    - name: type
      type: mapping_value
    - name: tags
      type: hstore_tags
    mapping:
      amenity:
      - __any__
      leisure:
      - __any__
      shop:
      - __any__
      tourism:
      - __any__
      building:
      - __any__
      natural:
      - __any__
      historic:
      - __any__
      information:
      - __any__
      government:
      - __any__
  landusages:
    type: polygon
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: validated_geometry
    - key: name
      name: name
      type: string
    - key: name:de
      name: name:de
      type: string
    - key: name:en
      name: name:en
      type: string
    - name: type
      type: mapping_value
    - name: class
      type: mapping_key
    - name: area
      type: area
    - key: building
      name: building
      type: boolint
    mapping:
      aeroway:
      - runway
      - taxiway
      - aerodrome
      - terminal
      - helipad
      - apron
      amenity:
      - university
      - school
      - college
      - library
      - parking
      - hospital
      - theatre
      - place_of_worship
      government:
      - prosecutor
      highway:
      - pedestrian
      landuse:
      - residential
      - retail
      - commercial
      - industrial
      - park
      - forest
      - railway
      - cemetery
      - grass
      - farmyard
      - farm
      - farmland
      - orchard
      - vineyard
      - wood
      - meadow
      - village_green
      - recreation_ground
      - allotments
      - quarry
      - basin
      - reservoir
      leisure:
      - park
      - garden
      - playground
      - golf_course
      - sports_centre
      - pitch
      - stadium
      - common
      - swimming_pool
      man_made:
      - pier
      military:
      - barracks
      natural:
      - wood
      - land
      - scrub
      - heath
      - water
      railway:
      - station
      - platform
      tourism:
      - zoo
      place:
      - island
      - islet
      - square
      waterway:
      - dock
      - riverbank
      landcover:
      - grass
  landusages_overlay:
    type: polygon
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: validated_geometry
    - key: name
      name: name
      type: string
    - name: type
      type: mapping_value
    - name: area
      type: area
    mapping:
      leisure:
      - nature_reserve
      natural:
      - wetland
      - marsh
  places:
    type: point
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - key: name
      name: name
      type: string
    - name: type
      type: mapping_value
    - args:
        values:
        - locality
        - suburb
        - hamlet
        - village
        - town
        - city
        - county
        - region
        - state
      name: z_order
      type: enumerate
    - key: population
      name: population
      type: integer
    mapping:
      place:
      - state
      - region
      - county
      - city
      - town
      - village
      - hamlet
      - suburb
      - locality

  roads:
    type: linestring
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - name: type
      type: mapping_value
    - args:
        suffixes:
          "Stra\xDFe": Str.
          "stra\xDFe": str.
      key: name
      name: name
      type: string_suffixreplace
    - key: tunnel
      name: tunnel
      type: boolint
    - key: bridge
      name: bridge
      type: boolint
    - key: oneway
      name: oneway
      type: direction
    - key: ref
      name: ref
      type: string
    - key: int_ref
      name: int_ref
      type: string
    - key: layer
      name: z_order
      type: wayzorder
    - key: access
      name: access
      type: string
    - key: service
      name: service
      type: string
    - name: class
      type: mapping_key
    - key: construction
      name: construction
      type: string
    - name: tags
      type: hstore_tags
    filters:
      exclude_tags:
      - [area, 'yes']
    mappings:
      aeroway:
        mapping:
          aeroway:
          - runway
          - taxiway
      railway:
        mapping:
          railway:
          - rail
          - tram
          - light_rail
          - subway
          - narrow_gauge
          - preserved
          - funicular
          - monorail
          - disused
          - platform
          - construction
      roads:
        mapping:
          highway:
          - motorway
          - motorway_link
          - trunk
          - trunk_link
          - primary
          - primary_link
          - secondary
          - secondary_link
          - tertiary
          - tertiary_link
          - road
          - path
          - track
          - service
          - footway
          - bridleway
          - cycleway
          - steps
          - pedestrian
          - living_street
          - unclassified
          - residential
          - raceway
          - construction
          man_made:
          - pier
          - groyne
  transport_areas:
    type: polygon
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - key: name
      name: name
      type: string
    - name: type
      type: mapping_value
    - key: ref
      name: ref
      type: string
    - key: subway
      name: subway
      type: boolint
    - key: train
      name: train
      type: boolint
    - key: tram
      name: tram
      type: boolint
    - key: light_rail
      name: light_rail
      type: boolint
    - key: rail
      name: rail
      type: boolint
    - key: station
      name: station
      type: string
    mapping:
      railway:
      - station
      - halt
      - tram_stop
  transport_points:
    type: point
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - key: name
      name: name
      type: string
    - name: type
      type: mapping_value
    - name: class
      type: mapping_key
    - key: ref
      name: ref
      type: string
    - key: subway
      name: subway
      type: boolint
    - key: train
      name: train
      type: boolint
    - key: tram
      name: tram
      type: boolint
    - key: light_rail
      name: light_rail
      type: boolint
    - key: rail
      name: rail
      type: boolint
    - key: station
      name: station
      type: string
    mapping:
      aeroway:
      - aerodrome
      - terminal
      - helipad
      - gate
      barrier:
      - block
      - bollard
      - cattle_grid
      - chain
      - cycle_barrier
      - entrance
      - horse_stile
      - gate
      - spikes
      - lift_gate
      - kissing_gate
      - fence
      - 'yes'
      - wire_fence
      - toll_booth
      - stile
      highway:
      - motorway_junction
      - turning_circle
      - bus_stop
      railway:
      - crossing
      - level_crossing
      - subway_entrance
      - station
      - halt
      - tram_stop
  waterways:
    type: linestring
    fields:
    - name: osm_id
      type: id
    - name: geometry
      type: geometry
    - key: name
      name: name
      type: string
    - name: type
      type: mapping_value
    - name: class
      type: mapping_key
    filters:
      exclude_tags:
      - [tunnel, 'yes']
    mapping:
      barrier:
      - ditch
      waterway:
      - stream
      - river
      - canal
      - drain
      - ditch


  networks:
    type: relation_member
    fields:
    - name: osm_id
      type: id
    - name: member
      type: member_id
    - name: index
      type: member_index
    - name: role
      type: member_role
    - name: type
      type: member_type
    - name: subname
      key: name
      type: string
      from_member: true
    - key: name
      name: name
      type: string
    - name: network
      key: network
      type: string
    mapping:
      type: ['network']

  master_routes:
    type: relation_member
    fields:
    - name: osm_id
      type: id
    - name: member
      type: member_id
    - name: index
      type: member_index
    - name: role
      type: member_role
    - name: type
      type: member_type
    - name: geometry
      type: geometry
    - name: subname
      key: name
      type: string
      from_member: true
    - key: name
      name: name
      type: string
    - name: tags
      type: hstore_tags
    mapping:
      route_master: [bus, train, tram, light_rail, railway]
  route_members:
    type: relation_member
    fields:
    - name: osm_id
      type: id
    - key: ref
      name: ref
      type: string
    - key: local_ref
      name: local_ref
      type: string
      from_member: true
    - name: member
      type: member_id
    - name: index
      type: member_index
    - name: role
      type: member_role
    - name: type
      type: member_type
    - name: geometry
      type: geometry
    - name: relname
      key: name
      type: string
    - name: name
      key: name
      type: string
      from_member: true
    mapping:
      route: [bus, train, tram, light_rail, railway]
  routes:
    type: relation
    fields:
    - name: osm_id
      type: id
    - key: ref
      name: ref
      type: string
    - name: tags
      type: hstore_tags
    mapping:
      route: [bus, train, tram, light_rail, railway]
